version: '3'
services:
  producer:
    build: .
    environment:
      KAFKA_HOST: 172.17.9.221:29093
      CLIENT_ID: <container_name>
      TOPIC: coordinates
    deploy:
      mode: replicated
      replicas: 10
