[package]
name = "consumer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kafka = "0.10.0"
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"