version: '3'

services:
  rust-app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

