version: '3'
services:
    angular:
        build: ./angular
        container_name: angular
        ports:
            - "4200:4200"
        networks:
            - front-net

    springboot:
        build: ./springboot
        container_name: springboot
        ports:
            - "8080:8080"
        environment:
            - 'SPRING_DATASOURCE_URL=jdbc:postgresql://172.17.4.182:5432/tracker'
            - 'SPRING_DATASOURCE_USERNAME=postgres'
            - 'SPRING_DATASOURCE_PASSWORD=postgres'
        networks:
            - front-net

networks:
    front-net:
